trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
  
  - script: |
      npm install -g @angular/cli
      npm install
    
  - script: npm run build-prod
    
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/'
      artifactName: 'drop'