# Node.js with Angular
trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build_Angular_App
  strategy:
    maxParallel: 1  # Correct way to limit parallelism
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli
      npm install
    displayName: 'Install dependencies'

  - script: npm run build-prod
    displayName: 'Build Angular App'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/online-course-ui/browser'
      artifactName: 'drop'
      publishLocation: 'Container'